# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-10 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('m2m_object_id', models.PositiveIntegerField(null=True)),
                ('type', models.CharField(db_index=True, max_length=8, null=True)),
                ('original_id', models.CharField(db_index=True, max_length=255)),
                ('content_hash', models.CharField(max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('m2m_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m2m_objecthistory_set', to='contenttypes.ContentType')),
            ],
        ),
    ]
