# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-09 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='restrictions_repr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='extendedgroup',
            name='type',
            field=models.CharField(choices=[('A', 'Authenticated'), ('I', 'IP Address based'), ('P', 'Attribute based'), ('E', 'Everybody')], max_length=1),
        ),
    ]
