# Generated by Django 3.1.14 on 2022-01-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20191209_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='manage',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='read',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='write',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='group',
            field=models.ForeignKey(limit_choices_to={'type': 'P'}, on_delete=django.db.models.deletion.CASCADE, to='access.extendedgroup'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='group',
            field=models.ForeignKey(limit_choices_to={'type': 'I'}, on_delete=django.db.models.deletion.CASCADE, to='access.extendedgroup'),
        ),
    ]
