version: '3.2'

services:
  mdid:
    build: ../.
    image: wmit/mdid:3.2
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    depends_on:
      - solr
      - rabbitmq
      - memcached
      - database
    environment:
      DB_USER: mdid
      DB_PASSWORD: supersecretpassword
      DB_NAME: mdid
  worker:
    build: ../.
    image: wmit/mdid:3.2
    command: python manage.py runworkers
    healthcheck:
      disable: true
    depends_on:
      - solr
      - rabbitmq
      - memcached
      - database
  solr:
    build: ../solr4/
    image: wmit/solr4-mdid
  rabbitmq:
    image: rabbitmq:3.6-alpine
  memcached:
    image: memcached:1.4-alpine
    command: memcached -m 128
  database:
    image: mysql:5.7
    healthcheck:
      test: mysql -umdid -psupersecretpassword mdid -e'SELECT 1'
    environment:
      MYSQL_DATABASE: mdid
      MYSQL_USER: mdid
      MYSQL_PASSWORD: supersecretpassword
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
