# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-10 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20190527_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mimetype',
            field=models.CharField(default='application/binary', max_length=128),
        ),
    ]
