# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-09 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20191010_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='credential_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='credential_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
