# Generated by Django 2.2.24 on 2022-01-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0014_auto_20220119_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='VRACore4FieldValue',
            fields=[
                ('fieldvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.FieldValue')),
                ('notes', models.TextField(blank=True)),
                ('dataDate', models.CharField(blank=True, max_length=255)),
                ('extent', models.TextField(blank=True)),
                ('href', models.TextField(blank=True)),
                ('pref', models.BooleanField(blank=True, null=True)),
                ('lang', models.CharField(blank=True, max_length=255)),
                ('refid', models.CharField(blank=True, max_length=255)),
                ('rules', models.CharField(blank=True, max_length=255)),
                ('source', models.TextField(blank=True)),
                ('vocab', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('num', models.CharField(blank=True, max_length=255)),
                ('count', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('relids', models.CharField(blank=True, max_length=255)),
                ('earliest_date', models.CharField(blank=True, max_length=255)),
                ('earliest_date_circa', models.BooleanField(blank=True, null=True)),
                ('latest_date', models.CharField(blank=True, max_length=255)),
                ('latest_date_circa', models.BooleanField(blank=True, null=True)),
            ],
            bases=('data.fieldvalue',),
        ),
    ]
