# Generated by Django 2.2.24 on 2022-01-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20191010_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='VRACore4FieldValue',
            fields=[
                ('fieldvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.FieldValue')),
                ('notes', models.TextField(blank=True)),
                ('dataDate', models.DateTimeField(auto_now=True)),
                ('extent', models.TextField(blank=True)),
                ('href', models.TextField(blank=True)),
                ('pref', models.BooleanField(blank=True, null=True)),
                ('refid', models.CharField(blank=True, max_length=255)),
                ('rules', models.CharField(blank=True, max_length=255)),
                ('source', models.TextField(blank=True)),
                ('vocab', models.CharField(blank=True, max_length=255)),
                ('lang', models.CharField(blank=True, max_length=255)),
            ],
            bases=('data.fieldvalue',),
        ),
    ]
