# Generated by Django 5.2.13 on 2026-04-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20220119_1055'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fieldvalue',
            new_name='data_fieldv_field_i_7fd1f5_idx',
            old_fields=('field', 'record', 'index_value'),
        ),
        migrations.RenameIndex(
            model_name='fieldvalue',
            new_name='data_fieldv_field_i_aa1d1e_idx',
            old_fields=('field', 'record', 'browse_value'),
        ),
        migrations.RenameIndex(
            model_name='fieldvalue',
            new_name='data_fieldv_record__b655ce_idx',
            old_fields=('record', 'field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='equivalent',
            field=models.ManyToManyField(blank=True, to='data.field'),
        ),
    ]
